import Head from "next/head";
import Link from "next/link";
import React, { useEffect, useRef, useState } from "react";
import DashboardHeader from "../../components/header/DashboardHeader";

import SideBar from "../../components/side-bar/SideBar";

import { subscriptionService } from "../../services/subscription.service";
import moment from "moment";
import FormSpinner from "../../components/Spinners/FormSpinner";
import { userService } from "../../services";
import ReactPaginate from "react-paginate";
import { CSVLink } from "react-csv";
import ExportExcel from "../../helpers/ExportExcel";
import ExportPdf from "../../helpers/ExportPdf";

export default function AllStock() {
  useEffect(() => {
    document.body.classList.remove("has--tabs");
  });

  const [allStock, setAllStock] = useState();
  const [option, setOption] = useState({ LastTradeTime: -1 });

  const [isLoading, setIsLoading] = useState(false);
  const [totalPage, setTotalPage] = useState(0);
  const [currentPage, setCurrentPage] = useState(1);
  const [search, setSearch] = useState("");

  const [csvDownloading,setCsvDownloading]=useState(false)
  const [xlsxDownloading,setXlsxDownloading]=useState(false)
  const [pdfDownloading,setPdfDownloading]=useState(false)
  const allStockRef = useRef();
  const [downloadStockData,setDownloadStockData]=useState([])
  const competitionHeaders = [
    {
      label: "Name",
      key: "Name",
    },
    { label: "Symbol", key: "Symbol" },
    { label: "Price(₦)", key: "Last" },
    { label: "Volume", key: "Volume" },
    { label: "Change(₦)", key: "Change" },
    { label: "Per Change(%)", key: "PerChange" },
    { label: "Last Update", key: "LastTradeTime" },

   
  ];

  useEffect(() => {
    getAllStock(currentPage, search, option);
  }, [option]);
  const getAllStock = (page, str, op) => {
    setIsLoading(true);
    userService
      .getAllStock(page, str, op)
      .then((res) => {
        if (res.success) {
          setAllStock(res.data);
          setTotalPage(res.totalPage);
        }
        setIsLoading(false);
      })
      .catch((err) => {
        setIsLoading(false);
        console.log(err);
      });
  };

  const handlePageClick = ({ selected }) => {
    setCurrentPage(selected + 1);
    getAllStock(selected + 1, search, option);
  };
  const handleSearch = (e) => {
    setSearch(e.target.value);
    setCurrentPage(1);
    getAllStock(1, e.target.value, option);
  };
  // const downloadStock = async () => {
  //   setDownloading(true);
  //   const { data } = await userService.downloadAllStock();
  //   setAllStockDownloading(data);
  //   setTimeout(() => {
  //     allStockRef.current.link.click();
  //     setDownloading(false);
  //   }, 2000);
  // };
  const downloadStock = async (str) => {
   
    const { data } =  await userService.downloadAllStock(search,option);
    setDownloadStockData(data);
    if (str == "csv") {
      setTimeout(() => {
        allStockRef.current.link.click();
        setCsvDownloading(false);
      }, 1000);
    } else if (str == "xlsx") {
      ExportExcel(competitionHeaders, data, "refferal");
      setXlsxDownloading(false)
    } else if (str == "pdf") {
      ExportPdf(competitionHeaders, data, "refferal");
      setPdfDownloading(false)
    }
  };
  return (
    <>
      <Head>
        <title>All Stock</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideBar />
      <div className="dashboard sideBarOpen">
        <DashboardHeader />
        <div className="contentWrapper">
          <div className="dashboard_content">
            <h1 className="dashboard__title">All Stocks</h1>
            <div className="btnLists manager">
              <ul>
                <li>
                  <form>
                    <input
                      type="text"
                      placeholder="Search by Stock name and symbol..."
                      onChange={(e) => handleSearch(e)}
                    />
                  </form>
                </li>
                <li>
            {csvDownloading ? (
              <Link href="javascript:void(0)">
                <a className="btn spinnerBtn">
                  <FormSpinner />
                </a>
              </Link>
            ) : (
              <Link href="javascript:void(0)">
                <a className="btn" onClick={() => {
                  setCsvDownloading(true)
                  downloadStock("csv")}}>
                  Export as CSV
                </a>
              </Link>
            )}
               <CSVLink
              style={{ display: "none" }}
              ref={allStockRef}
              headers={competitionHeaders}
              data={downloadStockData}
            >
              Download me
            </CSVLink>
          </li>
          <li>
            {xlsxDownloading ? (
              <Link href="javascript:void(0)">
                <a className="btn spinnerBtn">
                  <FormSpinner />
                </a>
              </Link>
            ) : (
              <Link href="javascript:void(0)">
                <a className="btn" onClick={() => {
                  setXlsxDownloading(true)
                  downloadStock("xlsx")
                }}>
                  Export as xlsx
                </a>
              </Link>
            )}

         
          </li>
          <li>
            {" "}
            {pdfDownloading ? (
              <Link href="javascript:void(0)">
                <a className="btn spinnerBtn">
                  <FormSpinner />
                </a>
              </Link>
            ) : (
              <Link href="javascript:void(0)">
                <a className="btn" onClick={() => {
                  setPdfDownloading(true)
                  downloadStock("pdf")
                }}>
                  Export as PDF
                </a>
              </Link>
            )}
          </li>
              </ul>
            </div>
            <div className="table--layout">
              {isLoading ? (
                <FormSpinner />
              ) : (
                <table>
                  <thead>
                    <tr>
                      <th
                        style={{ width: "3rem" }}
                        className="sorting__disabled"
                      >
                        Sr. No
                      </th>
                      <th
                        className={
                          option.Name == 1
                            ? "desc"
                            : option.Name == -1
                            ? "asc"
                            : ""
                        }
                        style={{ cursor: "pointer" }}
                        onClick={() => {
                          setOption({
                            Name: option.Name == 1 ? -1 : 1,
                          });
                        }}
                      >
                        Name
                      </th>
                      <th
                        className={
                          option.Symbol == 1
                            ? "desc"
                            : option.Symbol == -1
                            ? "asc"
                            : ""
                        }
                        style={{ cursor: "pointer" }}
                        onClick={() => {
                          setOption({
                            Symbol: option.Symbol == 1 ? -1 : 1,
                          });
                        }}
                      >
                        Symbol
                      </th>
                      <th
                        className={
                          option.Last == 1
                            ? "desc"
                            : option.Last == -1
                            ? "asc"
                            : ""
                        }
                        style={{ cursor: "pointer" }}
                        onClick={() => {
                          setOption({
                            Last: option.Last == 1 ? -1 : 1,
                          });
                        }}
                      >
                        Price (₦)
                      </th>
                      <th
                        className={
                          option.Volume == 1
                            ? "desc"
                            : option.Volume == -1
                            ? "asc"
                            : ""
                        }
                        style={{ cursor: "pointer" }}
                        onClick={() => {
                          setOption({
                            Volume: option.Volume == 1 ? -1 : 1,
                          });
                        }}
                      >
                        Volume
                      </th>

                      <th
                        className={
                          option.Change == 1
                            ? "desc"
                            : option.Change == -1
                            ? "asc"
                            : ""
                        }
                        style={{ cursor: "pointer" }}
                        onClick={() => {
                          setOption({
                            Change: option.Change == 1 ? -1 : 1,
                          });
                        }}
                      >
                        Change (₦)
                      </th>
                      <th
                        className={
                          option.PerChange == 1
                            ? "desc"
                            : option.PerChange == -1
                            ? "asc"
                            : ""
                        }
                        style={{ cursor: "pointer" }}
                        onClick={() => {
                          setOption({
                            PerChange: option.PerChange == 1 ? -1 : 1,
                          });
                        }}
                      >
                        Change (%)
                      </th>
                      <th
                        className={
                          option.LastTradeTime == 1
                            ? "desc"
                            : option.LastTradeTime == -1
                            ? "asc"
                            : ""
                        }
                        style={{ cursor: "pointer" }}
                        onClick={() => {
                          setOption({
                            LastTradeTime: option.LastTradeTime == 1 ? -1 : 1,
                          });
                        }}
                      >
                        Last Change
                      </th>

                      {/* <th style={{ width: "4rem" }} className="sorting__disabled">
                      Actions
                    </th> */}
                    </tr>
                  </thead>
                  <tbody>
                    {allStock &&
                      allStock.length > 0 &&
                      allStock.map((item, i) => {
                        return (
                          <tr key={i}>
                            <td>
                              {/* <input type="checkbox" /> */}
                              {(currentPage - 1) * 10 + i + 1}
                            </td>
                            <td>{item.Name}</td>
                            <td>{item.Symbol}</td>
                            <td>₦{item.Last?.toFixed(2)}</td>
                            <td>{item.Volume}</td>

                            <td>₦{item.Change?.toFixed(2)}</td>
                            <td>{item.PerChange}</td>

                            <td>{moment(item.LastTradeTime).format("ll")}</td>
                            {/* item.packageDuration == "trial" && */}
                          </tr>
                        );
                      })}
                  </tbody>
                </table>
              )}
              <ReactPaginate
                previousLabel={"prev"}
                nextLabel={"next"}
                breakLabel={"..."}
                breakClassName={"break-me"}
                pageCount={totalPage}
                forcePage={currentPage - 1}
                marginPagesDisplayed={2}
                pageRangeDisplayed={1}
                onPageChange={handlePageClick}
                containerClassName={"pagination"}
                subContainerClassName={"pages pagination"}
                activeClassName={"active"}
              />
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
