import React, { Fragment, useEffect, useState } from "react";
import DashboardHeader from "../../components/header/DashboardHeader";
import SideBar from "../../components/side-bar/SideBar";
import Head from "next/head";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";
import CountUp from "react-countup";
import { useDispatch, useSelector } from "react-redux";
//import BarChart from '../barchart';
// import PieChart from '../piechart';
import LineChart from "../linechart";
// import DoughnutChart from '../doughnut';
// import { useLoadScript } from '@react-google-maps/api';
// import { userService } from '../../services';
// import { async } from 'rxjs';
import { getStats } from "../../actions/dashboard";
import BarChart from "../barchart";
import DoughnutChart from "../doughnut";
import FormSpinner from "../../components/Spinners/FormSpinner";
import { userService } from "../../services";
import BlockUser from "../BlockUser";
import ActiveUser from "../ActiveUser";
import SubscribeUser from "../SubscribeUser";
import PaidSubscription from "../PaidSubscription";
import SubscriptionToday from "../SubscriptionToday";
export default function Dashboard() {
  const dispatch = useDispatch();
  const [isLoading, setIsloading] = useState(true);
  const [dayWise, setDayWise] = useState([]);
  const [userCount,setUserCount]=useState(0)

  const delay = 1;
  useEffect(() => {
    document.body.classList.add("has--tabs");
    UserDayWise()
    dispatch(getStats());
    let timer = setTimeout(() => setIsloading(false), delay * 1000);
    return () => {
      clearTimeout(timer);
    };
  }, []);
  let dashboardReducer = useSelector((state) => state.dashboardReducer);
  const UserDayWise = async () => {
    userService
      .getUserDayWise()
      .then((res) => {
        if (res.success) {
          setDayWise(res.data);
          setUserCount(res.usercount)
        } else {
          setDayWise([]);
          setUserCount(0)
        }
      })
      .catch((err) => {
        setDayWise([]);
        setUserCount(0)
      });
  };

  return (
    <>
      <Head>
        <title>Welcome Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Fragment>
        <SideBar />
        <div className="dashboard sideBarOpen">
          <DashboardHeader />
          <div className="contentWrapper">
            {dashboardReducer?.stats?.userCount ? (
              <div className="dashboard_content">
                {/* <h1 className="dashboard__title">Dashboard</h1> */}
                <div className="dashboard__tabs">
                  <div className="dashboard__row row--grid__4">
                    <div className="col--content users__col">
                      <div className="col--title">
                        <p>Total Users</p>
                      </div>
                      <div className="col--text">
                        <p className="counter">
                          <CountUp end={dashboardReducer?.stats?.userCount} />
                        </p>
                      </div>
                    </div>
                    <div className="col--content users__col">
                      <div className="col--title">
                        <p>Total Competitions</p>
                      </div>
                      <div className="col--text">
                        <p className="counter">
                          <CountUp end={dashboardReducer?.stats?.gameCount} />
                        </p>
                      </div>
                    </div>
                    {/* <div className="col--content users__col">
                    <div className="col--title">
                      <p>Total Revenue</p>
                    </div>
                    <div className="col--text">
                      <p className="counter">
                      ₦ <CountUp end={dashboardReducer?.stats?.total_subscriptions_revenue?.toFixed(2)} />
                      </p>
                    </div>
                  </div> */}
                    <div className="col--content users__col">
                      <div className="col--title">
                        <p>Total Subscriptions </p>
                      </div>
                      <div className="col--text">
                        <p className="counter">
                          <CountUp
                            end={dashboardReducer?.stats?.subscriptionCount}
                          />
                        </p>
                      </div>
                    </div>
                    <div className="col--content users__col">
                      <div className="col--title">
                        <p>Total Holidays</p>
                      </div>
                      <div className="col--text">
                        <p className="counter">
                          <CountUp
                            end={dashboardReducer?.stats?.holidayCount}
                          />
                        </p>
                      </div>
                    </div>

                    {/* <div className="col--content tickets--col">
                        <div className="col--title">
                          <p>New Tickets</p>
                        </div>
                        <div className="col--text">
                          <p className="counter">
                            <CountUp end={dashboardStats?.new_tickets} />
                          </p>
                        </div>
                      </div>

                      <div className="col--content col--2 no--icon">
                        <div className="col--title">
                          <p>Total Property Manager</p>
                        </div>
                        <div className="col--text">
                          <DoughnutChart />
                        </div>
                      </div>
                      <div className="col--content col--2 no--icon">
                        <div className="col--title">
                          <p>New Tickets</p>
                        </div>
                        <div className="col--text">
                          <LineChart />
                        </div>
                      </div>
                      <div className="col--content col--2 tickets--col no--icon">
                        <div className="col--title">
                          <p>Ticket Status</p>
                        </div>
                        <div className="col--image">
                          <PieChart />
                        </div>
                      </div> */}
                  </div>
                  <div
                    className="dashboard__row row--grid__4"
                    style={{ marginTop: "20px" }}
                  >
                      {dashboardReducer?.stats?.blockUser && (
                      <div className="col--content col--2 no--icon">
                        <div className="col--title">
                          <p>
                            This Week Subscriptions Revenue :- 
                            <strong>
                            ₦{dashboardReducer?.stats?.subtotalWeek
                                ?.toString()
                                .replace(/\B(?=(\d{3})+(?!\d))/g, ",")}
                            </strong>
                          </p>
                        </div>
                        <div className="col--text">
                          <SubscriptionToday
                            userData={dashboardReducer?.stats?.subscriptionHistory}
                            lable='Subscriptions'
                          />
                          {/* <BarChart data={dashboardReducer?.stats?.subData} /> */}
                        </div>
                      </div>
                    )}
                     {dashboardReducer?.stats?.blockUser && (
                      <div className="col--content col--2 no--icon">
                        <div className="col--title">
                          <p>
                            This Week User Registers :  
                            <strong>
                             {dashboardReducer?.stats?.subUserWeek
                                ?.toString()
                                .replace(/\B(?=(\d{3})+(?!\d))/g, ",")}
                            </strong>
                          </p>
                        </div>
                        <div className="col--text">
                          <SubscriptionToday
                            userData={dashboardReducer?.stats?.userWeek}
                            lable='Users'
                          />
                          {/* <BarChart data={dashboardReducer?.stats?.subData} /> */}
                        </div>
                      </div>
                    )}
                
                  </div>
                  <div className="dashboard__row row--grid__4" style={{marginTop:'20px'}}>
                {dayWise && <div className="col--content col--1 no--icon">
                    <div className="col--title">
                      <p>Today Trades Trek Unique (User) Logs :-  <strong> {userCount}</strong></p>
                    </div>
                    <div className="col--text">
                      <LineChart subData={dayWise} />
                    </div>
                  </div>}
                  </div>
                  <div
                    className="dashboard__row row--grid__4"
                    style={{ marginTop: "20px" }}
                  >
                      {dashboardReducer?.stats?.blockUser && (
                      <div className="col--content col--2 no--icon">
                        <div className="col--title">
                          <p>
                            User Block/Unblock :-{" "}
                            <strong>
                              {dashboardReducer?.stats?.userCount
                                ?.toString()
                                .replace(/\B(?=(\d{3})+(?!\d))/g, ",")}
                            </strong>
                          </p>
                        </div>
                        <div className="col--text">
                          <BlockUser
                            userData={dashboardReducer?.stats?.blockUser}
                          />
                          {/* <BarChart data={dashboardReducer?.stats?.subData} /> */}
                        </div>
                      </div>
                    )}
                    {dashboardReducer?.stats?.statusActive && (
                      <div className="col--content col--2 no--icon">
                        <div className="col--title">
                          <p>
                            Users Active/Inactive :-{" "}
                            <strong>
                              {dashboardReducer?.stats?.userCount
                                ?.toString()
                                .replace(/\B(?=(\d{3})+(?!\d))/g, ",")}
                            </strong>
                          </p>
                        </div>
                        <div className="col--text">
                          <ActiveUser
                            userData={dashboardReducer?.stats?.statusActive}
                          />
                          {/* <BarChart data={dashboardReducer?.stats?.subData} /> */}
                        </div>
                      </div>
                    )}
                  </div>
                  <div
                    className="dashboard__row row--grid__4"
                    style={{ marginTop: "20px" }}
                  >
                      {dashboardReducer?.stats?.blockUser && (
                      <div className="col--content col--2 no--icon">
                        <div className="col--title">
                          <p>
                            User Subscribe/Unsubscribe:-{" "}
                            <strong>
                              {dashboardReducer?.stats?.userCount
                                ?.toString()
                                .replace(/\B(?=(\d{3})+(?!\d))/g, ",")}
                            </strong>
                          </p>
                        </div>
                        <div className="col--text">
                          <SubscribeUser
                            userData={dashboardReducer?.stats?.subscribedUser}
                          />
                          {/* <BarChart data={dashboardReducer?.stats?.subData} /> */}
                        </div>
                      </div>
                    )}
                    {dashboardReducer?.stats?.paidSubscription && (
                      <div className="col--content col--2 no--icon">
                        <div className="col--title">
                          <p>
                            Users Paid Subscription/Basic :-{" "}
                            <strong>
                              {dashboardReducer?.stats?.userCount
                                ?.toString()
                                .replace(/\B(?=(\d{3})+(?!\d))/g, ",")}
                            </strong>
                          </p>
                        </div>
                        <div className="col--text">
                          <PaidSubscription
                            userData={dashboardReducer?.stats?.paidSubscription}
                          />
                          {/* <BarChart data={dashboardReducer?.stats?.subData} /> */}
                        </div>
                      </div>
                    )}
                  </div>
                  
                  <div
                    className="dashboard__row row--grid__4"
                    style={{ marginTop: "20px" }}
                  >
                    {dashboardReducer?.stats?.subData?.length > 0 && (
                      <div className="col--content col--2 no--icon">
                        <div className="col--title">
                          <p>
                            Subscriptions Revenue :-{" "}
                            <strong>
                              ₦{" "}
                              {dashboardReducer?.stats?.total_subscriptions_revenue
                                ?.toFixed(2)
                                ?.toString()
                                .replace(/\B(?=(\d{3})+(?!\d))/g, ",")}
                            </strong>
                          </p>
                        </div>
                        <div className="col--text">
                          <BarChart
                            subData={dashboardReducer?.stats?.subData}
                          />
                        </div>
                      </div>
                    )}
                    {dashboardReducer?.stats?.userData && (
                      <div className="col--content col--2 no--icon">
                        <div className="col--title">
                          <p>
                            All Users :-{" "}
                            <strong>
                              {dashboardReducer?.stats?.userCount
                                ?.toString()
                                .replace(/\B(?=(\d{3})+(?!\d))/g, ",")}
                            </strong>
                          </p>
                        </div>
                        <div className="col--text">
                          <DoughnutChart
                            userData={dashboardReducer?.stats?.userData}
                          />
                          {/* <BarChart data={dashboardReducer?.stats?.subData} /> */}
                        </div>
                      </div>
                    )}
                  </div>
                  {/* <div className="dashboard__row row--grid__8" style={{marginTop:'20px'}}>
               {dashboardReducer?.stats?.userData&& <div className="col--content col--2 no--icon">
                    <div className="col--title">
                      <p>All Games :-  <strong>{dashboardReducer?.stats?.gameCount?.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",")}</strong></p>
                    </div>
                    <div className="col--text">
                     <LineChart />
                    </div>
                  </div>}
               </div> */}
                </div>
              </div>
            ) : (
              <div
                className="dashboard_content"
                style={{
                  display: "flex",
                  height: "100vh",
                  justifyContent: "center",
                  justifyContent: "center",
                }}
              >
                <FormSpinner />
              </div>
            )}
          </div>
        </div>
      </Fragment>
    </>
  );
}
