import Head from "next/head";
import { Select, Table, Input } from "@mantine/core";
import SideBar from "../../components/side-bar/SideBar";
import { stockService } from "../../services/stock.service";
import { List, ListItem, ListItemText } from "@mui/material";
import { toast, ToastContainer } from "react-toastify";
import React, { useEffect, useState } from "react";

export default function Sectors() {
  const [stockSectors, setStockSectors] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [selectedSector, setSelectedSector] = useState("");
  const [stocksUnderSector, setStocksUnderSectors] = useState([]);

  useEffect(() => {
    stockService
      .getAllStockSectors()
      .then((res) => {
        if (res.success) {
          setStockSectors(res.data);
        }
        setIsLoading(false);
      })
      .catch((err) => {
        setIsLoading(false);
      });
  }, []);

  useEffect(() => {
    if (!selectedSector) return;
    stockService
      .getStocksUnderSector(selectedSector)
      .then((res) => {
        if (res.success) {
          setStocksUnderSectors(res.data);
        }
        setIsLoading(false);
      })
      .catch((err) => {
        setIsLoading(false);
      });
  }, [selectedSector]);

  console.log(stocksUnderSector);
  return (
    <>
      <Head>
        <title>Stock sectors </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideBar />
      <div className="dashboard sideBarOpen">
        <div className="contentWrapper">
          <div className="dashboard_content">
            <h1 className="dashboard__title">Stock sectors</h1>

            <Select
              label=""
              placeholder="Pick  sector"
              data={stockSectors}
              value={selectedSector}
              onChange={setSelectedSector}
            />

            <br />
            <br />
            <br />

            {isLoading ? (
              <p>Loading</p>
            ) : stocksUnderSector.length > 0 ? (
              <SectorList data={stocksUnderSector} />
            ) : (
              <></>
            )}
          </div>
        </div>
      </div>
    </>
  );
}

function SectorList({ data }) {
  return (
    <List
      sx={{
        width: "100%",
        maxWidth: 400,
        maxHeight: 500,
        bgcolor: "background.paper",
        overflow: 'scroll'
      }}
    >
      {data.map((e) => (
        <ListItem key={e}>
          <ListItemText primary={e} />
        </ListItem>
      ))}
    </List>
  );
}
