import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React, { useEffect, useState } from "react";
import DashboardHeader from "../../components/header/DashboardHeader";
import { Tab, Tabs, TabList, TabPanel } from "react-tabs";
import "react-tabs/style/react-tabs.css";
import SideBar from "../../components/side-bar/SideBar";
import Portfolio from "../../components/portfolio/Portfolio";
import TradeHistory from "../../components/portfolio/TradeHistory";
import { useRouter } from "next/router";

export default function UserPortfolio() {
  const router=useRouter()

  useEffect(()=>{
          if(router.query.id){
                    console.log(router.query.id)
          }

  },[router])

  
  return (
    <>
      <Head>
        <title>Subscription Details</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideBar />
      <div className="dashboard sideBarOpen">
        <DashboardHeader />
        <div className="contentWrapper">
          
          <div className="dashboard_content">
        
          <div className="table--layout">


                    </div>

         
          </div>
        </div>
      </div>
    </>
  );
}
