import React, { Fragment, useEffect, useState } from 'react';
import DashboardHeader from '../../components/header/DashboardHeader';
import SideBar from '../../components/side-bar/SideBar';
import Head from 'next/head';
import HomeView from '../../components/home/HomeView';
import UsersList from '../../components/users/UsersList';
import { toast } from 'react-toastify';
import { FormSpinner } from '../../components/Spinners/FormSpinner';
import { confirmAlert } from 'react-confirm-alert'; // Import
import { userService } from '../../services';
import Modal from 'react-modal';
import { async } from 'rxjs';
import Link from 'next/link';
export default function Users() {
  const [bulkActions, setBulkActions] = useState(false);
  const [filterAction, setFilterAction] = useState(false);
  return (
    <>
      <Head>
        <title>Welcome Users</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Fragment>
        <SideBar />
        <div className="dashboard sideBarOpen">
          <DashboardHeader />
          <div className="contentWrappers">
            <div className="dashboard_content">
              <h1 className="dashboard__title">All Users</h1>
              <UsersList />
            </div>
          </div>
        </div>
      </Fragment>
    </>
  );
}
