import Head from 'next/head';
import React, { useEffect } from 'react';
import Login from '../components/login/LoginView';
import Header from '../components/header/Header';
import { useRouter } from 'next/router';
import { userService } from '../services';

export default function Home() {
  const router = useRouter();
  useEffect(() => {
    if (userService.userValue) {
      router.push('/admin/dashboard');
    }
  }, []);
  return (
    <div className="">
      <Head>
        <title>Admin Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Login />
    </div>
  );
}
